### ISSUE TITLE
Conditional mock of "external service"

### ISSUE THREAD

**Issue by MattiasAsplund** [LogicAppUnit/TestingFramework#33]
Service Bus has been "mocked" by a Docker image (in this case Apache ActiveMQ Artemis).

It would be advisable to be able to turn the internal mocking behaviour on and off, so that potential standins (external to the Logic App, but internal from an inward looking perspective) could be used.

Turning internal mocking off would in this case mean that AMQP 1.0 protocol behaviour, when sending Service Bus messages, could be tested.

**Comment by mark-abrams** [comment]
Hi @MattiasAsplund , are you using a built-in connector to connect to Service Bus, or a managed API connector?

**Comment by MattiasAsplund** [comment]
I have been thinking about an Azure Service Bus alternative (AMQP 1.0 based
service) surrounding the test context, where assertions would be made
against an actual message queue. Like a "real" service although kind of
mocked)

I guess it would have to be the built-in connector, I haven't really tried
that part yet.


Mattias

Den ons 6 mars 2024 kl 17:24 skrev Mark Abrams ***@***.***>:
